//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis.Radius
{
    using System;
    using System.Collections.Generic;
    
    public partial class kiralama_tarifes
    {
        public kiralama_tarifes()
        {
            this.makine_masraf_tanims2 = new HashSet<makine_masraf_tanims2>();
            this.servicehesaps = new HashSet<servicehesap>();
        }
    
        public int id { get; set; }
        public int makine_id { get; set; }
        public string tarife_kodu { get; set; }
        public string calisma_tipi { get; set; }
        public decimal tutar { get; set; }
        public bool saatlik { get; set; }
        public bool iptal { get; set; }
    
        public virtual makine_caris makine_caris { get; set; }
        public virtual ICollection<makine_masraf_tanims2> makine_masraf_tanims2 { get; set; }
        public virtual ICollection<servicehesap> servicehesaps { get; set; }
    }
}
