//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis.Radius
{
    using System;
    using System.Collections.Generic;
    
    public partial class makine_caris
    {
        public makine_caris()
        {
            this.kiralama_tarifes = new HashSet<kiralama_tarifes>();
            this.makine_kullanicis = new HashSet<makine_kullanicis>();
            this.makine_masraf_hesaps2 = new HashSet<makine_masraf_hesaps2>();
            this.makine_masraf_tanims2 = new HashSet<makine_masraf_tanims2>();
            this.servicemakines = new HashSet<servicemakine>();
            this.makine_servis_sayacs = new HashSet<makine_servis_sayacs>();
            this.makine_masraf_girislers = new HashSet<makine_masraf_girislers>();
            this.servicehesaps = new HashSet<servicehesap>();
        }
    
        public int makine_id { get; set; }
        public string adi { get; set; }
        public string plaka { get; set; }
        public string aciklama { get; set; }
        public decimal son_sayac { get; set; }
        public decimal tarife_saat { get; set; }
        public decimal tarife_gun { get; set; }
        public decimal tarife_hafta { get; set; }
        public decimal tarife_ay { get; set; }
        public decimal toplam_calisma_saat { get; set; }
        public decimal toplam_calisma_gun { get; set; }
        public decimal toplam_calisma_hafta { get; set; }
        public decimal toplam_calisma_ay { get; set; }
        public decimal toplam_masraf_teorik { get; set; }
        public decimal toplam_masraf_gercek { get; set; }
        public decimal toplam_gelir { get; set; }
        public decimal servis_sayaci { get; set; }
        public bool iptal { get; set; }
        public decimal toplam_sayac { get; set; }
        public int toplam_dakika { get; set; }
    
        public virtual ICollection<kiralama_tarifes> kiralama_tarifes { get; set; }
        public virtual ICollection<makine_kullanicis> makine_kullanicis { get; set; }
        public virtual ICollection<makine_masraf_hesaps2> makine_masraf_hesaps2 { get; set; }
        public virtual ICollection<makine_masraf_tanims2> makine_masraf_tanims2 { get; set; }
        public virtual ICollection<servicemakine> servicemakines { get; set; }
        public virtual ICollection<makine_servis_sayacs> makine_servis_sayacs { get; set; }
        public virtual ICollection<makine_masraf_girislers> makine_masraf_girislers { get; set; }
        public virtual ICollection<servicehesap> servicehesaps { get; set; }
    }
}
