//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis.Radius
{
    using System;
    using System.Collections.Generic;
    
    public partial class makine_masraf_girislers
    {
        public int id { get; set; }
        public int makine_id { get; set; }
        public int masraf_id { get; set; }
        public decimal miktar { get; set; }
        public string birim { get; set; }
        public decimal tutar { get; set; }
        public System.DateTime tarih { get; set; }
        public string aciklama { get; set; }
        public string belge_no { get; set; }
        public bool sifirla { get; set; }
        public string @operator { get; set; }
        public bool iptal { get; set; }
    
        public virtual makine_caris makine_caris { get; set; }
        public virtual makine_masrafs makine_masrafs { get; set; }
    }
}
