//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis.Radius
{
    using System;
    using System.Collections.Generic;
    
    public partial class makine_masrafs
    {
        public makine_masrafs()
        {
            this.alim_detays = new HashSet<alim_detays>();
            this.makine_masraf_girislers = new HashSet<makine_masraf_girislers>();
            this.makine_masraf_hesaps2 = new HashSet<makine_masraf_hesaps2>();
            this.makine_masraf_tanims2 = new HashSet<makine_masraf_tanims2>();
            this.makine_servis_sayacs = new HashSet<makine_servis_sayacs>();
        }
    
        public int MasrafID { get; set; }
        public string adi { get; set; }
        public string aciklama { get; set; }
        public decimal giris { get; set; }
        public decimal cikis { get; set; }
        public decimal bakiye { get; set; }
        public decimal birim_maliyet { get; set; }
        public string birim { get; set; }
        public int birim_id { get; set; }
        public bool iptal { get; set; }
    
        public virtual ICollection<alim_detays> alim_detays { get; set; }
        public virtual cihaz_birims cihaz_birims { get; set; }
        public virtual ICollection<makine_masraf_girislers> makine_masraf_girislers { get; set; }
        public virtual ICollection<makine_masraf_hesaps2> makine_masraf_hesaps2 { get; set; }
        public virtual ICollection<makine_masraf_tanims2> makine_masraf_tanims2 { get; set; }
        public virtual ICollection<makine_servis_sayacs> makine_servis_sayacs { get; set; }
    }
}
