//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis.Radius
{
    using System;
    using System.Collections.Generic;
    
    public partial class makine_masraf_tanims2
    {
        public int tanim_id { get; set; }
        public int makine_id { get; set; }
        public int masraf_id { get; set; }
        public int tarifeid { get; set; }
        public decimal masraf_saat { get; set; }
        public string birim { get; set; }
        public string aciklama { get; set; }
        public bool iptal { get; set; }
    
        public virtual kiralama_tarifes kiralama_tarifes { get; set; }
        public virtual makine_caris makine_caris { get; set; }
        public virtual makine_masrafs makine_masrafs { get; set; }
    }
}
