//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis.Radius
{
    using System;
    using System.Collections.Generic;
    
    public partial class makine_masraf_hesaps2
    {
        public int id { get; set; }
        public int serviceid { get; set; }
        public int hesap_id { get; set; }
        public int makine_id { get; set; }
        public int masraf_id { get; set; }
        public int dakika { get; set; }
        public decimal son_sayac { get; set; }
        public decimal calisma_saati { get; set; }
        public string tarifekodu { get; set; }
        public decimal miktar { get; set; }
        public decimal tutar { get; set; }
        public decimal gelir { get; set; }
        public string birim { get; set; }
        public string aciklama { get; set; }
        public System.DateTime tarih { get; set; }
        public bool iptal { get; set; }
    
        public virtual makine_caris makine_caris { get; set; }
        public virtual service service { get; set; }
        public virtual servicehesap servicehesap { get; set; }
        public virtual makine_masrafs makine_masrafs { get; set; }
    }
}
