//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis.Radius
{
    using System;
    using System.Collections.Generic;
    
    public partial class makine_kullanicis
    {
        public int id { get; set; }
        public int makine_id { get; set; }
        public string kullanici { get; set; }
        public System.DateTime atama { get; set; }
        public Nullable<System.DateTime> cikarma { get; set; }
        public bool iptal { get; set; }
    
        public virtual makine_caris makine_caris { get; set; }
    }
}
