//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis.Radius
{
    using System;
    using System.Collections.Generic;
    
    public partial class servicehesap_ops
    {
        public int HesapID { get; set; }
        public Nullable<int> makine_id { get; set; }
        public string tarife_kodu { get; set; }
        public string tarife_tipi { get; set; }
        public Nullable<int> tarifeid { get; set; }
        public decimal baslangic { get; set; }
        public decimal bitis { get; set; }
        public decimal calisma_saati { get; set; }
        public decimal yeni_sayac { get; set; }
        public decimal toplam_sayac { get; set; }
        public int dakika { get; set; }
        public string sure_aciklama { get; set; }
        public System.DateTime baslangic_tarih { get; set; }
        public System.DateTime bitis_tarih { get; set; }
        public string servis_kimlik { get; set; }
        public string IslemParca { get; set; }
        public decimal birim_fiyat { get; set; }
        public Nullable<decimal> Tutar { get; set; }
        public Nullable<decimal> KDV { get; set; }
        public Nullable<decimal> Yekun { get; set; }
        public string Aciklama { get; set; }
        public System.DateTime TarihZaman { get; set; }
        public decimal adet { get; set; }
        public string birim { get; set; }
        public Nullable<int> cihaz_id { get; set; }
        public Nullable<bool> sinirsiz { get; set; }
        public string cihaz_adi { get; set; }
        public Nullable<int> cihaz_gsure { get; set; }
        public string Urun_Cinsi { get; set; }
        public Nullable<System.DateTime> Urun_GarantiBaslangic { get; set; }
        public Nullable<System.DateTime> Urun_GarantiBitis { get; set; }
        public Nullable<int> Urun_GarantiSuresi { get; set; }
        public string Urun_Aciklama { get; set; }
        public string Urun_Kimlik { get; set; }
        public bool onay { get; set; }
        public Nullable<System.DateTime> Onay_tarih { get; set; }
        public Nullable<int> stok_id { get; set; }
        public Nullable<decimal> birim_maliyet { get; set; }
        public Nullable<decimal> toplam_maliyet { get; set; }
        public bool iptal { get; set; }
        public string inserted { get; set; }
        public string updated { get; set; }
        public string deleted { get; set; }
        public string Firma { get; set; }
        public string kullanici { get; set; }
    }
}
