//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis.Radius
{
    using System;
    using System.Collections.Generic;
    
    public partial class service_maliyets
    {
        public int id { get; set; }
        public int servisid { get; set; }
        public int hesapid { get; set; }
        public decimal tutar { get; set; }
        public bool iptal { get; set; }
    
        public virtual servicehesap servicehesap { get; set; }
    }
}
