//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis.Radius
{
    using System;
    using System.Collections.Generic;
    
    public partial class servicemakine
    {
        public int id { get; set; }
        public int makine_id { get; set; }
        public int serviceid { get; set; }
        public decimal calisma_saati { get; set; }
        public decimal toplam_sayac { get; set; }
        public int toplam_dakika { get; set; }
        public string tarife_kodu { get; set; }
        public decimal yekun { get; set; }
        public decimal maliyet { get; set; }
        public bool iptal { get; set; }
    
        public virtual makine_caris makine_caris { get; set; }
        public virtual service service { get; set; }
    }
}
